### PR TITLE
Update messages.py

### PR DESCRIPTION
**Pull request by 3gstudent**
Hi Jordan,

When we connect to the Exchange Powershell, the output command results are incomplete.

Here is the my test code:

```
wsman = WSMan(server=host, username=username, password=password, port=80, path="PowerShell", ssl=False, auth="kerberos", cert_validation=False)     
with wsman, RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:
    ps = PowerShell(pool)                  
    ps.add_cmdlet("Get-Mailbox").add_parameter("-Identity", "administrator")
    output = ps.invoke()
    print("[+] OUTPUT:\n%s" % "\n".join([str(s) for s in output]))
```

This is the output:

In fact, the complete result is as follows:

So I rewrite the [messages.py](https://github.com/jborean93/pypsrp/blob/master/src/pypsrp/messages.py) to output more complete results.

This is the new output:

### CODE REVIEW

**Comment by jborean93** [comment]
I'm not sure why this is needed, you are doing `str(output)` which is simply going to get the `<ToString>` value of the output object which will of course not have all the properties that were returned in the string value.

It sounds like you want to combine `output.adapted_properties` and `output.extended_properties` on each of the output objects and then format them the way you wish. Unfortunately the UX is pretty poor for dealing with these complex objects but it shouldn't need a manual check in the deserializer code.

**Comment by 3gstudent** [comment]
Yes, I want to combine the output and get the complete result. Is there a better way to combine output?

**Comment by jborean93** [comment]
You would need to go through the `adapted_properties` and `extended_properties` of the output object(s). This will contain the keys you are looking for and can be formatted how you wish.

**Comment by 3gstudent** [comment]
OK. Thanks for your advice.

**Pull request closed without merging**
